baseURL = "https://jbolik.github.io/"
canonifyURLs = false
title = "Jannis Bolik's Stat Blog"
languageCode = "en-us"
theme = "PaperMod"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[params]
  env = "production"
  description = "Statistics, probability, and ML notes."
  author = "Jannis Bolik"
  defaultTheme = "light"        # dark/light
  disableThemeToggle = true
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowToc = true
  TocOpen = true
  mainSections = ["posts"]     # ensure posts appear on /

[params.assets]
  css = ["css/custom.css"]


[markup]
  [markup.goldmark.renderer]
    unsafe = true              # allow raw HTML (needed for KaTeX+Giscus)
  [markup.highlight]
    noClasses = false          # better theming

[outputs]
  home = ["HTML", "RSS", "JSON"]  # JSON enables search (Pagefind later)

[permalinks]
  posts = "/:year/:month/:slug/"

[minify]
  minifyOutput = true
